services:
  backend:
    build:
      context: ./backend  
    ports:
      - "8000:8000"  
    volumes:
      - ./backend:/app  
    environment:
      - PYTHONUNBUFFERED=1  
    depends_on:
      - db 

  frontend:
    build:
      context: ./frontend  
    ports:
      - "3000:3000"  
    volumes:
      - ./frontend:/app  
    environment:
      - CHOKIDAR_USEPOLLING=true  

  db:
    image: mongo:5.0  
    container_name: mongodb
    ports:
      - "27017:27017"  
    volumes:
      - ./data:/data/db  
